# Config file for recompiling patches for Harvest Moon 64 Recompiled

[input]
# Paths are relative to the location of this config file.
elf_path = "patches/patches.elf"
output_func_path = "RecompiledPatches"
single_file_output = true
# Allow absolute symbols to be used as jump targets.
use_absolute_symbols = true
# Tell the recompiler to write the output binary.
output_binary_path = "patches/patches.bin"
# Do not emit warnings for unpaired LO16 values, as clang produces many of them.
unpaired_lo16_warnings = false
# Allow exporting functions and events for mods to use.
allow_exports = true
# Disable strict patch mode for now (no symbol files yet)
strict_patch_mode = false
